# radiantbluetechnolgoies/rialto-viewer

FROM radiantbluetechnologies/rialto-cesium
MAINTAINER mpg@flaxen.com

COPY ./build.sh /tmp/rialto-viewer/build.sh
RUN /tmp/rialto-viewer/build.sh

CMD /bin/bash

