# Tuple Builder Container
FROM centos:centos6
MAINTAINER mpg@flaxen.com

RUN yum -y install nodejs ant && curl -L https://api.github.com/repos/mpgerlek/cesium/tarbal > /tmp/cesium.tar.gz && tar xvf /tmp/cesium.tar.gz && ant /tmp/cesium combine ?? && 


