name: Rialto
description: The Rialto Point Cloud Viewer
dependencies:
  browser: any
  core_elements: any
  paper_elements: any
  polymer: any
  three:
    git:
      ref: 
      url: https://github.com/threedart/three.dart
  vector_math: any
transformers:
- polymer
