name: Rialto
description: The Rialto Point Cloud Viewer
dependencies:
  browser: any
  core_elements: any
  crypto: any
  http: any
  paper_elements: any
  polymer: any
  three:
    git: https://github.com/threedart/three.dart
  vector_math: any
transformers:
- polymer
