- layers:
    - bing:
        type: bing_base_imagery
        style: Aerial

    - cloud:
        type: pointcloud
        url: http://rialto01.dev.ossim.org/tiles/tiledserp18

- wps:
    url: http://rialto.dev.ossim.org/geoserver/ows

